services:
  - type: web
    name: kimathi-systems
    env: docker
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /index.php
    envVars:
      - key: SMTP_HOST
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SITE_EMAIL
        sync: false